import { EXPO_ROUTER_APP_ROOT, EXPO_ROUTER_IMPORT_MODE, EXPO_PUBLIC_SUPABASE_URL, EXPO_PUBLIC_SUPABASE_ANON_KEY } from '@env';
console.log('EXPO_ROUTER_APP_ROOT:', EXPO_ROUTER_APP_ROOT);
console.log('EXPO_ROUTER_IMPORT_MODE:', EXPO_ROUTER_IMPORT_MODE);
console.log('EXPO_PUBLIC_SUPABASE_URL:', EXPO_PUBLIC_SUPABASE_URL);
console.log('EXPO_PUBLIC_SUPABASE_ANON_KEY:', EXPO_PUBLIC_SUPABASE_ANON_KEY);