/*
  # Add 100 UK Driving Theory Test Questions

  1. New Data
    - Insert 100 comprehensive UK driving theory test questions
    - Cover various categories: road signs, speed limits, hazards, parking, etc.
    - Include detailed explanations for each question
    - Set appropriate difficulty levels

  2. Question Coverage
    - Road signs and markings
    - Speed limits and stopping distances
    - Hazard awareness
    - Vehicle safety checks
    - Traffic laws and regulations
    - Parking and waiting restrictions
    - Vulnerable road users
    - Weather conditions
    - Vehicle control and handling
    - Motorway driving
*/

-- Insert 100 UK driving theory test questions
INSERT INTO questions (id, question, options, correct_answer, explanation, category, difficulty) VALUES
(1, 'What is the national speed limit for cars on a dual carriageway?', '["60 mph", "70 mph", "80 mph", "50 mph"]', 1, 'The national speed limit for cars on dual carriageways is 70 mph.', 'speed_limits', 'easy'),
(2, 'What does a circular blue sign with a white arrow pointing left mean?', '["No left turn", "Compulsory left turn", "Left turn ahead", "One way left"]', 1, 'A circular blue sign with a white arrow indicates a compulsory direction.', 'road_signs', 'medium'),
(3, 'When should you use hazard warning lights?', '["When parking illegally", "When your vehicle has broken down", "When driving in heavy rain", "When overtaking"]', 1, 'Hazard warning lights should be used when your vehicle has broken down or is causing an obstruction.', 'vehicle_safety', 'easy'),
(4, 'What is the minimum tread depth for car tyres?', '["1.6mm", "2.0mm", "1.2mm", "2.5mm"]', 0, 'The minimum legal tread depth for car tyres in the UK is 1.6mm.', 'vehicle_safety', 'medium'),
(5, 'What does a red circular sign mean?', '["Warning", "Information", "Prohibition", "Mandatory"]', 2, 'Red circular signs indicate prohibition - something you must not do.', 'road_signs', 'easy'),
(6, 'When can you use the right-hand lane of a three-lane motorway?', '["Only for overtaking", "For normal driving", "When traffic is heavy", "For emergency vehicles only"]', 0, 'The right-hand lane of a motorway should only be used for overtaking.', 'motorway', 'medium'),
(7, 'What is the speed limit in a built-up area unless otherwise stated?', '["20 mph", "30 mph", "40 mph", "50 mph"]', 1, 'The default speed limit in built-up areas is 30 mph unless otherwise indicated.', 'speed_limits', 'easy'),
(8, 'What should you do if you see a school crossing patrol showing a stop sign?', '["Slow down and proceed with caution", "Stop and wait", "Sound your horn", "Drive around them"]', 1, 'You must stop and wait when a school crossing patrol shows a stop sign.', 'vulnerable_road_users', 'easy'),
(9, 'What is the stopping distance at 50 mph in good conditions?', '["53 metres", "73 metres", "96 metres", "125 metres"]', 1, 'The total stopping distance at 50 mph is 73 metres (thinking distance + braking distance).', 'stopping_distances', 'hard'),
(10, 'When should you check your mirrors?', '["Only when changing lanes", "Every 30 seconds", "Before signalling, manoeuvring or changing speed", "Only when reversing"]', 2, 'You should check your mirrors before signalling, manoeuvring, or changing speed.', 'vehicle_control', 'medium'),
(11, 'What does a triangular road sign indicate?', '["Information", "Warning", "Prohibition", "Instruction"]', 1, 'Triangular signs are warning signs that alert you to hazards ahead.', 'road_signs', 'easy'),
(12, 'When are you allowed to use your horn?', '["Between 11:30 pm and 7:00 am in built-up areas", "To alert other road users of your presence", "When someone cuts you off", "Never in built-up areas"]', 1, 'You should only use your horn to alert others of your presence when necessary for safety.', 'traffic_laws', 'medium'),
(13, 'What should you do when approaching a zebra crossing with people waiting to cross?', '["Speed up to get past", "Sound your horn", "Be prepared to stop", "Flash your headlights"]', 2, 'You should be prepared to stop and give way to pedestrians at zebra crossings.', 'vulnerable_road_users', 'easy'),
(14, 'When can you park on the right-hand side of the road at night?', '["Never", "In a one-way street", "If there are no yellow lines", "Only in residential areas"]', 1, 'You can only park on the right-hand side of the road at night in a one-way street.', 'parking', 'medium'),
(15, 'What is the maximum penalty for drink driving?', '["£1,000 fine", "6 months imprisonment", "Unlimited fine and 6 months imprisonment", "Community service"]', 2, 'Drink driving can result in an unlimited fine, 6 months imprisonment, and driving ban.', 'traffic_laws', 'hard'),
(16, 'When should you use your headlights during the day?', '["Never", "In poor visibility conditions", "Only in winter", "When it is raining lightly"]', 1, 'Use headlights during the day when visibility is seriously reduced.', 'weather_conditions', 'medium'),
(17, 'What is the purpose of ABS (Anti-lock Braking System)?', '["To stop the car faster", "To prevent the wheels from locking", "To reduce fuel consumption", "To improve steering"]', 1, 'ABS prevents the wheels from locking under heavy braking, maintaining steering control.', 'vehicle_safety', 'medium'),
(18, 'When must you give way to buses?', '["Always", "When they are pulling out from a bus stop", "Never", "Only in bus lanes"]', 1, 'You should give way to buses when they are signalling to pull out from a bus stop.', 'traffic_laws', 'medium'),
(19, 'What should you do if you break down on a motorway?', '["Stay in your vehicle", "Move to the hard shoulder and exit the vehicle on the left", "Put on hazard lights and stay in the car", "Stand behind your vehicle"]', 1, 'Move to the hard shoulder, exit on the left side, and stand away from your vehicle and the carriageway.', 'motorway', 'medium'),
(20, 'What is the maximum speed limit for learner drivers?', '["60 mph", "70 mph", "Same as qualified drivers", "50 mph"]', 2, 'Learner drivers must follow the same speed limits as qualified drivers.', 'speed_limits', 'easy'),
(21, 'What does a white line painted across the road mean?', '["Give way", "Stop", "No entry", "Speed limit"]', 0, 'A white line across the road indicates a give way line where you must give way to traffic on the major road.', 'road_markings', 'easy'),
(22, 'When driving in fog, you should:', '["Use full beam headlights", "Use dipped headlights", "Use hazard warning lights", "Drive without lights"]', 1, 'In fog, use dipped headlights to avoid dazzling other drivers and to see the road markings.', 'weather_conditions', 'medium'),
(23, 'What is the speed limit on a single carriageway road?', '["50 mph", "60 mph", "70 mph", "40 mph"]', 1, 'The national speed limit on single carriageway roads is 60 mph for cars.', 'speed_limits', 'easy'),
(24, 'When should you use the MSM routine?', '["Only when parking", "Before any manoeuvre", "Only on motorways", "When reversing only"]', 1, 'MSM (Mirror, Signal, Manoeuvre) should be used before any manoeuvre to ensure safety.', 'vehicle_control', 'medium'),
(25, 'What does a red traffic light mean?', '["Prepare to stop", "Stop", "Give way", "Proceed with caution"]', 1, 'A red traffic light means stop and wait behind the stop line.', 'traffic_lights', 'easy'),
(26, 'How close can you park to a junction?', '["5 metres", "10 metres", "15 metres", "20 metres"]', 1, 'You must not park within 10 metres of a junction unless in an authorised parking space.', 'parking', 'medium'),
(27, 'What should you do when you see a pedestrian with a white stick?', '["Sound your horn", "Flash your lights", "Give them plenty of room", "Drive past quickly"]', 2, 'A white stick indicates a blind or partially sighted person. Give them plenty of room and be patient.', 'vulnerable_road_users', 'easy'),
(28, 'When are you allowed to cross a solid white line in the centre of the road?', '["Never", "To overtake a slow-moving vehicle", "To avoid an obstruction", "When turning right"]', 2, 'You may cross a solid white line to avoid a stationary obstruction or to enter or leave a side road or property.', 'road_markings', 'hard'),
(29, 'What is the typical stopping distance at 30 mph?', '["23 metres", "53 metres", "73 metres", "96 metres"]', 0, 'The typical stopping distance at 30 mph is 23 metres in good conditions.', 'stopping_distances', 'medium'),
(30, 'When should you not overtake?', '["On a dual carriageway", "When approaching a junction", "On a straight road", "In good weather"]', 1, 'You should not overtake when approaching a junction as visibility may be limited and traffic may be turning.', 'vehicle_control', 'medium'),
(31, 'What does a yellow box junction mean?', '["No stopping", "Keep the junction clear", "Slow down", "Give way"]', 1, 'A yellow box junction means keep the junction clear - only enter if your exit is clear.', 'road_markings', 'medium'),
(32, 'When driving at night, when should you dip your headlights?', '["When following another vehicle", "When meeting oncoming traffic", "Both of the above", "Never"]', 2, 'Dip your headlights when following another vehicle or meeting oncoming traffic to avoid dazzling other drivers.', 'night_driving', 'easy'),
(33, 'What is the speed limit in a school zone during school hours?', '["20 mph", "30 mph", "40 mph", "Variable"]', 0, 'School zones typically have a 20 mph speed limit during school hours for child safety.', 'speed_limits', 'medium'),
(34, 'When can you use a mobile phone while driving?', '["In an emergency", "When hands-free", "Never", "When stationary in traffic"]', 1, 'You can only use a mobile phone while driving if it is hands-free and does not require you to hold it.', 'traffic_laws', 'medium'),
(35, 'What should you do if your vehicle starts to skid?', '["Brake hard", "Steer into the skid", "Accelerate", "Turn the steering wheel quickly"]', 1, 'If your vehicle skids, steer gently into the direction of the skid to regain control.', 'vehicle_control', 'hard'),
(36, 'How often should you check your tyre pressure?', '["Once a month", "Once a week", "Once a year", "Only when they look flat"]', 1, 'Tyre pressure should be checked at least once a week when tyres are cold.', 'vehicle_safety', 'medium'),
(37, 'What does a pelican crossing allow pedestrians to do?', '["Cross when they want", "Control the traffic lights", "Cross with priority", "Wait for a gap in traffic"]', 1, 'A pelican crossing allows pedestrians to control the traffic lights using a push button.', 'vulnerable_road_users', 'easy'),
(38, 'When should you use your car horn in a built-up area?', '["Between 11:30 pm and 7:00 am", "Never between 11:30 pm and 7:00 am", "Anytime", "Only in emergencies"]', 1, 'You must not use your horn in a built-up area between 11:30 pm and 7:00 am except in an emergency.', 'traffic_laws', 'medium'),
(39, 'What is the maximum speed for a car towing a trailer on a motorway?', '["50 mph", "60 mph", "70 mph", "40 mph"]', 1, 'The maximum speed for a car towing a trailer on a motorway is 60 mph.', 'speed_limits', 'medium'),
(40, 'When should you use rear fog lights?', '["In heavy rain", "When visibility is less than 100 metres", "At night", "In bright sunlight"]', 1, 'Rear fog lights should only be used when visibility is seriously reduced to less than 100 metres.', 'weather_conditions', 'medium'),
(41, 'What does a green traffic light mean?', '["Go if safe to do so", "Go immediately", "Prepare to stop", "Give way"]', 0, 'A green traffic light means go if it is safe to do so and your exit is clear.', 'traffic_lights', 'easy'),
(42, 'How should you signal when slowing down or stopping?', '["Use brake lights", "Use hazard lights", "Use indicators", "Use arm signals"]', 0, 'Brake lights automatically signal to following traffic that you are slowing down or stopping.', 'vehicle_control', 'easy'),
(43, 'What is the drink-drive limit in England and Wales?', '["35 micrograms per 100ml of breath", "50 micrograms per 100ml of breath", "80 micrograms per 100ml of breath", "No limit"]', 0, 'The drink-drive limit in England and Wales is 35 micrograms of alcohol per 100ml of breath.', 'traffic_laws', 'hard'),
(44, 'When joining a motorway, you should:', '["Stop and wait for a gap", "Use the acceleration lane to match traffic speed", "Drive slowly until you find a gap", "Force your way into traffic"]', 1, 'Use the acceleration lane to build up speed and match the speed of traffic on the motorway.', 'motorway', 'medium'),
(45, 'What should you do when approaching traffic lights that have been green for some time?', '["Speed up to get through", "Maintain your speed", "Be prepared to stop", "Flash your lights"]', 2, 'Be prepared to stop as the lights may change to amber and red.', 'traffic_lights', 'medium'),
(46, 'When is it legal to reverse from a side road into a main road?', '["Never", "When traffic is light", "During daylight hours only", "When you have a clear view"]', 0, 'It is never legal to reverse from a side road into a main road as it is dangerous.', 'vehicle_control', 'medium'),
(47, 'What does a flashing amber traffic light mean?', '["Stop", "Go", "Proceed with caution", "Give way"]', 2, 'A flashing amber light means proceed with caution and give way to pedestrians who may be crossing.', 'traffic_lights', 'medium'),
(48, 'How far should you stay behind the vehicle in front in good conditions?', '["1 second", "2 seconds", "3 seconds", "4 seconds"]', 1, 'In good conditions, maintain a 2-second gap behind the vehicle in front.', 'vehicle_control', 'medium'),
(49, 'What should you do if you miss your motorway exit?', '["Reverse back to the exit", "Stop and turn around", "Continue to the next exit", "Cross the central reservation"]', 2, 'If you miss your motorway exit, continue to the next exit and find an alternative route.', 'motorway', 'easy'),
(50, 'When should you use dipped headlights during the day?', '["Never", "In poor visibility", "When it is sunny", "Only in winter"]', 1, 'Use dipped headlights during the day when visibility is poor due to weather conditions.', 'weather_conditions', 'medium'),
(51, 'What is the speed limit for cars in a residential area with street lighting?', '["20 mph", "30 mph", "40 mph", "50 mph"]', 1, 'The speed limit in residential areas with street lighting is typically 30 mph unless otherwise signed.', 'speed_limits', 'easy'),
(52, 'When should you use your parking brake?', '["Only on hills", "Every time you park", "Only at night", "Only in car parks"]', 1, 'You should use your parking brake every time you park to prevent the vehicle from rolling.', 'vehicle_safety', 'easy'),
(53, 'What does a blue circular sign with a white bicycle symbol mean?', '["No cycling", "Cycle route", "Compulsory cycle lane", "Cycle parking"]', 2, 'A blue circular sign with a white bicycle indicates a compulsory cycle lane.', 'road_signs', 'medium'),
(54, 'When driving in icy conditions, you should:', '["Use normal braking", "Brake gently and early", "Brake hard to stop quickly", "Not use brakes at all"]', 1, 'In icy conditions, brake gently and much earlier than normal to avoid skidding.', 'weather_conditions', 'medium'),
(55, 'What is the maximum fine for not wearing a seatbelt?', '["£100", "£500", "£1000", "£2000"]', 1, 'The maximum fine for not wearing a seatbelt is £500.', 'traffic_laws', 'medium'),
(56, 'When should you not park your vehicle?', '["Near a school entrance", "On a bend", "Near a junction", "All of the above"]', 3, 'You should not park near school entrances, on bends, or near junctions as it creates hazards.', 'parking', 'easy'),
(57, 'What should you do when following a large vehicle?', '["Stay close to see better", "Drop back to increase your view", "Overtake immediately", "Flash your lights"]', 1, 'Drop back to increase your view of the road ahead and give yourself more time to react.', 'vehicle_control', 'medium'),
(58, 'When are you allowed to wait in a yellow box junction?', '["Never", "When turning right and blocked by oncoming traffic", "When traffic is heavy", "For up to 5 minutes"]', 1, 'You may wait in a yellow box junction only when turning right and your exit is clear but you are prevented from completing the turn by oncoming traffic.', 'road_markings', 'hard'),
(59, 'What does a red and white triangular sign mean?', '["No entry", "Give way", "Stop", "Road works"]', 1, 'A red and white triangular sign means give way to traffic on the major road.', 'road_signs', 'easy'),
(60, 'When driving on a motorway, what should you do if you feel tired?', '["Open the windows", "Turn up the radio", "Stop at the next service area", "Drink coffee"]', 2, 'If you feel tired on a motorway, stop at the next service area and rest.', 'motorway', 'easy'),
(61, 'What is the speed limit for goods vehicles over 7.5 tonnes on a single carriageway?', '["40 mph", "50 mph", "60 mph", "70 mph"]', 1, 'Goods vehicles over 7.5 tonnes are limited to 50 mph on single carriageways.', 'speed_limits', 'hard'),
(62, 'When should you use hazard warning lights while driving?', '["In heavy rain", "When driving slowly", "Only when stationary", "To warn of a hazard ahead"]', 3, 'Use hazard warning lights while driving only to warn other traffic of a hazard ahead.', 'vehicle_safety', 'medium'),
(63, 'What should you do when approaching a roundabout?', '["Speed up", "Give way to traffic from the right", "Stop and wait", "Sound your horn"]', 1, 'When approaching a roundabout, give way to traffic from the right that is already on the roundabout.', 'traffic_laws', 'medium'),
(64, 'How should you position your vehicle when turning right at a crossroads?', '["Keep to the left", "Position just left of centre", "Position in the centre", "Keep to the right"]', 1, 'When turning right at crossroads, position your vehicle just left of the centre line.', 'vehicle_control', 'medium'),
(65, 'What does a white arrow painted on the road mean?', '["Direction to follow", "Lane designation", "Speed limit", "Parking area"]', 0, 'A white arrow painted on the road indicates the direction traffic should follow in that lane.', 'road_markings', 'easy'),
(66, 'When is it safe to overtake on the left?', '["Never", "When traffic is moving slowly in queues", "On motorways only", "In one-way streets"]', 1, 'It is safe to overtake on the left when traffic is moving slowly in queues and the left lane is moving faster.', 'vehicle_control', 'hard'),
(67, 'What should you do if you see a person with a guide dog?', '["Sound your horn", "Drive past quickly", "Be patient and give them time", "Flash your lights"]', 2, 'Be patient and give people with guide dogs plenty of time and space to cross safely.', 'vulnerable_road_users', 'easy'),
(68, 'When should you check your blind spots?', '["Before changing lanes", "Before overtaking", "Before turning", "All of the above"]', 3, 'Check your blind spots before changing lanes, overtaking, or turning to ensure no other road users are there.', 'vehicle_control', 'medium'),
(69, 'What is the speed limit on most motorways?', '["60 mph", "70 mph", "80 mph", "Variable"]', 1, 'The speed limit on most UK motorways is 70 mph for cars.', 'speed_limits', 'easy'),
(70, 'When should you use full beam headlights?', '["In built-up areas", "When no other traffic is around", "During the day", "In fog"]', 1, 'Use full beam headlights only when no other traffic is around to avoid dazzling other drivers.', 'night_driving', 'medium'),
(71, 'What should you do when driving through a ford?', '["Drive through quickly", "Test your brakes afterwards", "Use high revs", "Avoid using brakes"]', 1, 'After driving through a ford, test your brakes gently as they may be less effective when wet.', 'weather_conditions', 'medium'),
(72, 'When are you allowed to use the hard shoulder on a motorway?', '["When traffic is heavy", "In an emergency only", "To overtake slow traffic", "Never"]', 1, 'The hard shoulder should only be used in an emergency or breakdown situation.', 'motorway', 'easy'),
(73, 'What does a circular sign with a red border mean?', '["Warning", "Information", "Prohibition or restriction", "Mandatory instruction"]', 2, 'A circular sign with a red border indicates a prohibition or restriction.', 'road_signs', 'medium'),
(74, 'How should you drive when roads are wet?', '["At normal speed", "Reduce speed and increase following distance", "Use cruise control", "Brake harder"]', 1, 'In wet conditions, reduce speed and increase following distance as stopping distances are longer.', 'weather_conditions', 'medium'),
(75, 'What is the purpose of rumble strips?', '["To slow traffic down", "To alert drivers to a hazard", "To mark lane boundaries", "To improve grip"]', 1, 'Rumble strips are designed to alert drivers to a hazard ahead through noise and vibration.', 'road_features', 'medium'),
(76, 'When should you signal left when leaving a roundabout?', '["Before entering", "After passing the exit before yours", "At your exit", "Never"]', 1, 'Signal left after passing the exit before the one you intend to take.', 'vehicle_control', 'medium'),
(77, 'What should you do if your vehicle breaks down in a tunnel?', '["Stay with your vehicle", "Switch on hazard lights and leave the vehicle", "Try to restart the engine", "Wait for help inside"]', 1, 'If your vehicle breaks down in a tunnel, switch on hazard lights and leave the vehicle if it is safe to do so.', 'vehicle_safety', 'hard'),
(78, 'When driving behind a cyclist, you should:', '["Stay close behind", "Give them plenty of room", "Sound your horn", "Overtake immediately"]', 1, 'Give cyclists plenty of room when following or overtaking them.', 'vulnerable_road_users', 'easy'),
(79, 'What does a speed limit sign in a red circle mean?', '["Minimum speed", "Maximum speed", "Advisory speed", "Average speed"]', 1, 'A speed limit sign in a red circle indicates the maximum speed allowed.', 'road_signs', 'easy'),
(80, 'When should you use your mirrors most frequently?', '["Before signalling", "Before manoeuvring", "Before changing speed", "All of the above"]', 3, 'Use your mirrors frequently, especially before signalling, manoeuvring, or changing speed.', 'vehicle_control', 'medium'),
(81, 'What should you do when you see double white lines with a broken line on your side?', '["Never cross", "You may cross to overtake", "Stop immediately", "Sound your horn"]', 1, 'When there is a broken white line on your side, you may cross to overtake if it is safe to do so.', 'road_markings', 'medium'),
(82, 'How should you approach a zebra crossing?', '["Speed up if no one is crossing", "Be prepared to stop", "Sound your horn", "Flash your lights"]', 1, 'Always be prepared to stop at a zebra crossing as pedestrians have right of way.', 'vulnerable_road_users', 'easy'),
(83, 'What is the typical reaction time for an alert driver?', '["0.5 seconds", "0.67 seconds", "1 second", "2 seconds"]', 1, 'The typical reaction time for an alert driver is about 0.67 seconds (two-thirds of a second).', 'stopping_distances', 'hard'),
(84, 'When should you not use cruise control?', '["On motorways", "In wet conditions", "During long journeys", "In light traffic"]', 1, 'Do not use cruise control in wet conditions as you need full control of the vehicle.', 'vehicle_control', 'medium'),
(85, 'What does a brown tourist sign indicate?', '["Road works", "Tourist attraction", "Diversion route", "Parking area"]', 1, 'Brown signs indicate tourist attractions and places of interest.', 'road_signs', 'easy'),
(86, 'When driving at 70 mph, what is your stopping distance in good conditions?', '["53 metres", "73 metres", "96 metres", "120 metres"]', 2, 'At 70 mph in good conditions, the stopping distance is 96 metres.', 'stopping_distances', 'hard'),
(87, 'What should you do when driving past parked cars?', '["Maintain normal speed", "Slow down and be prepared to stop", "Sound your horn", "Use hazard lights"]', 1, 'Slow down when driving past parked cars as doors may open or pedestrians may step out.', 'vehicle_control', 'medium'),
(88, 'When are you allowed to park facing against the traffic flow?', '["At night only", "In one-way streets only", "Never", "In residential areas"]', 1, 'You may park facing against the traffic flow only in one-way streets.', 'parking', 'medium'),
(89, 'What should you do if you are being followed too closely?', '["Speed up", "Brake suddenly", "Gradually slow down", "Change lanes immediately"]', 2, 'If being followed too closely, gradually slow down to increase the gap in front and encourage the following driver to overtake.', 'vehicle_control', 'medium'),
(90, 'When should you use your vehicle horn?', '["To say thank you", "To alert others of your presence", "To show annoyance", "To hurry other drivers"]', 1, 'Use your horn only to alert other road users of your presence when necessary for safety.', 'traffic_laws', 'easy'),
(91, 'What is the speed limit for cars on a motorway in wet conditions?', '["50 mph", "60 mph", "70 mph", "Reduce speed as appropriate"]', 3, 'In wet conditions, reduce your speed as appropriate for the conditions, even if below the speed limit.', 'weather_conditions', 'medium'),
(92, 'When should you use parking lights?', '["When parking at night", "When driving in fog", "When parking during the day", "Never"]', 0, 'Use parking lights when parking at night on roads with a speed limit over 30 mph.', 'night_driving', 'medium'),
(93, 'What does a keep left sign mean?', '["No right turn", "Compulsory direction", "Advisory route", "One way street"]', 1, 'A keep left sign indicates a compulsory direction that traffic must follow.', 'road_signs', 'easy'),
(94, 'When driving in snow, you should:', '["Use normal tyres", "Reduce speed and use gentle movements", "Brake hard when necessary", "Use cruise control"]', 1, 'In snow, reduce speed and use gentle steering, braking, and acceleration movements.', 'weather_conditions', 'medium'),
(95, 'What should you do when approaching a level crossing?', '["Speed up to cross quickly", "Stop and look both ways", "Sound your horn", "Flash your lights"]', 1, 'Always stop, look, and listen before crossing a level crossing, even if no train is visible.', 'hazard_awareness', 'medium'),
(96, 'When is it legal to use a hand-held mobile phone while driving?', '["When stationary in traffic", "In an emergency to call 999", "Never", "When hands-free is not available"]', 2, 'It is never legal to use a hand-held mobile phone while driving, including when stationary in traffic.', 'traffic_laws', 'medium'),
(97, 'What should you do when you see a horse and rider on the road?', '["Sound your horn", "Pass quickly", "Slow down and give plenty of room", "Flash your lights"]', 2, 'Slow down and give horses and riders plenty of room as horses can be easily startled.', 'vulnerable_road_users', 'easy'),
(98, 'When should you use the two-second rule?', '["Only in good weather", "In all driving conditions", "Only on motorways", "Only during the day"]', 1, 'Use the two-second rule in all normal driving conditions to maintain a safe following distance.', 'vehicle_control', 'medium'),
(99, 'What does a green arrow traffic light mean?', '["Go in any direction", "Go in the direction of the arrow only", "Prepare to stop", "Give way"]', 1, 'A green arrow means you may go in the direction shown by the arrow only.', 'traffic_lights', 'medium'),
(100, 'When driving on a smart motorway, what do red X signs mean?', '["Slow down", "Lane closed", "Hazard ahead", "Exit only"]', 1, 'Red X signs on smart motorways mean the lane is closed and you must not drive in that lane.', 'motorway', 'medium')
ON CONFLICT (id) DO UPDATE SET
  question = EXCLUDED.question,
  options = EXCLUDED.options,
  correct_answer = EXCLUDED.correct_answer,
  explanation = EXCLUDED.explanation,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  updated_at = now();